### ISSUE TITLE
go-demo service/container keeps failing... same issue that was "closed"

### ISSUE THREAD

**Issue by tarakmodi** [vfarcic/go-demo#9] opened 2017-09-16 19:22 UTC
I am running into the exact same problem. I have created the 3 nodes on AWS using docker machine. The Mongo DB starts up fine but the the go-demo app keeps failing. I have kept the security group wide open to allow all traffic.

**Comment by vfarcic** [comment] 2017-09-16 20:12
That is almost certainly caused by problems in Overlay network. Can you confirm that both TCP and UDP ports are open?

You can test it by creating a new service based on `alpine` (e.g. `docker service --mode global --name test --network [THE_NAME_OF_THE_NETWORK_GO_DEMO_IS_ATTACHED_TO] alpine sleep 10000000`). Make it global so that it runs on all nodes. Enter into one of the replicas (it must be on a different node than where DB is running) and execute:

```
apk add --update drill

drill db

drill tasks.db
```

Please post the output. Feel free to ping me on DevOps20 Slack channel if you fail to execute drill. If you're not already registered to the channel, please go to slack.devops20toolkit.com . My user is `vfarcic`.

**Comment by tarakmodi** [comment] 2017-09-16 20:42
All TCP and UDP ports are open. I have a rule in the AWS security group to allow all traffic.

Here's the output from drill. Nothing in the answer section :(.

/ # drill go-demo-db
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 40920
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0 
;; QUESTION SECTION:
;; go-demo-db.	IN	A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
.	60	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2017091601 1800 900 604800 86400

;; ADDITIONAL SECTION:

;; Query time: 31 msec
;; SERVER: 127.0.0.11
;; WHEN: Sat Sep 16 20:39:25 2017
;; MSG SIZE  rcvd: 103

**Comment by tarakmodi** [comment] 2017-09-16 20:43
Here is the go-demo network inspect output:

docker network inspect go-demo
[
    {
        "Name": "go-demo",
        "Id": "bd4cm93dqqbcl1is21qxdidvj",
        "Created": "2017-09-16T20:31:11.692063177Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.2.0/24",
                    "Gateway": "10.0.2.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "f45b9dd43ec6882e332d69884004c5e8de82f344fa3eebd08fca8ceebebcd285": {
                "Name": "util.84g4hnywhnydaioao93r1a77o.vhdszypezeo3mihcys1s3lhzq",
                "EndpointID": "386b9e60892063f909f7949e99a244de02bb76ec0e2b03ffaa0d2b86da46d786",
                "MacAddress": "02:42:0a:00:02:09",
                "IPv4Address": "10.0.2.9/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4099"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "node-1-9b96ed518fdc",
                "IP": "34.201.32.242"
            }
        ]
    }
]

**Comment by tarakmodi** [comment] 2017-09-16 20:43
And the go-demo-db service inspect:

docker service inspect --pretty go-demo-db

ID:		t0c0oy1j4tzmjwxega8ig5yeb
Name:		go-demo-db
Service Mode:	Replicated
 Replicas:	1
Placement:
UpdateConfig:
 Parallelism:	1
 On failure:	pause
 Max failure ratio: 0
ContainerSpec:
 Image:		mongo
Resources:
Networks: go-demo 
Endpoint Mode:	vip

**Comment by tarakmodi** [comment] 2017-09-16 20:46
Here are the docker services:

ID            NAME        MODE        REPLICAS  IMAGE
t0c0oy1j4tzm  go-demo-db  replicated  1/1       mongo
u0kug0sifm5l  util        global      3/3       alpine

**Comment by vfarcic** [comment] 2017-09-16 20:56
Something is hijacking communication through the Overlay network. When you drilled `go-demo-db` you got the response from `nstld.verisign-grs.com`, not an IP Overlay network assigned to that service.

Is that a corporate AWS account? It might be Route 53 or some other AWS service you're running in that region. Did you create a fresh security group for DM instances or you used an existing one? Is there any other AWS service you're using that might interfere with DM VMs?

**Comment by tarakmodi** [comment] 2017-09-16 21:00
Yes, it does appear that something is hijacking it. 

Two of my alpine util containers have IPs of 10.0.2.7 and 10.0.2.9. I am not able to ping them from inside either container either although they can ping themselves.

This is a personal AWS account.  The security group is a fresh one just for this book. 

No, I am not using any other service.

**Comment by vfarcic** [comment] 2017-09-16 21:03
Do you use that AWS account for anything else? There must be some service that is messing with networking.

**Comment by tarakmodi** [comment] 2017-09-16 21:05
No... Just EC2.

**Comment by tarakmodi** [comment] 2017-09-16 21:12
I could start a gotomeeting and share my screen

**Comment by vfarcic** [comment] 2017-09-16 21:16
I need to go to sleep now. It's close to midnight in my time zone. We can have a chat with screen sharing on Monday if that suits you. In the meantime, why don't you give *Docker For AWS* a try? It is a preferable way to create a Swarm cluster and it's free (except AWS costs).

**Comment by vfarcic** [comment] 2017-09-16 21:19
This might help: https://youtu.be/uWTL8gwzZz4

**Comment by tarakmodi** [comment] 2017-09-16 21:20
ok... will do.  thank you! 

If I can't make any progress, we can screen share on Monday.

**Comment by tarakmodi** [comment] 2017-09-17 01:29
It worked with Docker for AWS :).... now I will try to figure out how to make it work using docker machine locally.... 

Thanks for your help. I will ping you as I continue to work through your 2.1 book...

**Comment by vfarcic** [comment] 2017-09-17 10:46
I'll close this ticket since it's not directly related to *Go Demo*. Please ping me on Slack if you run into any problem.

**Closed as completed by vfarcic** 2017-09-17 10:46 UTC
